### ISSUE TITLE
Some links to member websites on membership page are missing "http://"

### ISSUE THREAD

**Issue by brittag** [doubleunion/doubleunion-dot-org#28]
At the bottom of [the membership page](http://www.doubleunion.org/membership), in the list of members, clicking on some people leads to URLs like "http://www.doubleunion.org/www.alightholder.com", and clicking on some other people leads to reloading the page ("http://www.doubleunion.org/membership"). At some point we might want to figure out how to systematically make those links lead to expected places. :)

**Comment by azurelunatic** [comment]
The http://www.doubleunion.org/www.alightholder.com one I know -- when
there's a link like

&lt;a href="www.alightholder.com"&gt;text&lt/a&gt;

it gets interpreted as a relative link (slap it on the end of the current
page) rather than an absolute link.

The fix for that is to make sure that all the personal page links have
http:// or https:// on them.

**Comment by azurelunatic** [comment]
Aha, and the other ones that are causing the page to reload are in the
format

&lt;a href&gt;name&lt;/a&gt;

Though I'm not entirely sure how they got that way...

**Comment by azurelunatic** [comment]
... woops, I had skipped over reading the subject! Sorry to get splainey up in here.

**Comment by Imperiopolis** [comment]
Fixed with #70!
